# Use a base image with Python
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy only specific files needed for the setup
COPY requirements.txt ./

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code and other necessary files
COPY . .

# Set the entry point or command to run your application
CMD ["python", "yahoo-api.py"]
