version: '3.9'

volumes:
  postgres_data: 

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
      POSTGRES_USER: postgres
    ports:
      - "5432" 
    volumes:
      - /var/lib/postgresql/data #Anonymous volume
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data  Mount the volume


  api:
    build: .
    ports:
      - "3330:3330"
    volumes:
      - ./controller/:/app/controller
      - ./repo/:/app/repo
      - ./utils/:/app/utils
      - ./services/:/app/services
      - /node_modules
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
    depends_on:
      db:
        condition: service_healthy
  view:
    build: ./View
    volumes:
      - ./View:/app
      - /node_modules
    
    command:  bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - api
      - db
    

      
  external_services:
    build: ./external_services
    volumes:
      - ./external_services:/app
      - /venv
    command: python yahoo-api.py
    expose:
    - "5000"

    
