version: '3.9'

volumes:
  postgres_data: 

services:
  my-postgres:
    image: postgres:16
    
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5439:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mount the volume
